Wire 1357: operator permissions (#13)
- Go script to keep permissions up do date in helm chart - helm chart changes to make it work
- Operator securityContext and kubernetes rbac permissions in helm chart
- Added make helm command to generate rbac manifest in helm chart and updated CI script to check that helm rbac is up to date

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -34,6 +34,17 @@ jobs:
         if: github.event_name == 'release'
         run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
 
+      - name: Generate Helm charts
+        run: make helm
+
+      - name: Verify charts directory is up-to-date
+        run: |
+             if ! git diff --exit-code -- charts/; then
+               echo "::error ::charts/ is out of sync — please commit the updated files."
+               git --no-pager diff -- charts/
+               exit 1
+             fi
+
       - name: Build Go binary amd64
         run: go build -ldflags "-s -w -X main.GitCommit=$GITHUB_SHA -X main.GitRef=$GITHUB_REF -X main.Version=${RELEASE_TAG:-commit-$GITHUB_SHA}" -o bin/castware-operator-amd64 cmd/main.go
         env:
